image:
  repository: postgres
  tag: "12"
  pullPolicy: IfNotPresent

postgresql:
  username: "postgres"
  existingSecret: "{{ .Release.Name }}-postgresql-secret"  # Ссылка на Secret
  database: "postgres"
  port: 5432

persistence:
  enabled: true
  size: 50Gi              # Больше места
  storageClass: "ssd"      # Быстрое хранилище
  accessMode: ReadWriteOnce

resources:
  requests:
    memory: "2Gi"          # Больше RAM для продакшена
    cpu: "500m"
  limits:
    memory: "4Gi"
    cpu: "2"

service:
  type: ClusterIP
  port: 5432