image:
  repository: postgres
  tag: "12"
  pullPolicy: IfNotPresent

postgresql:
  username: postgres
  password: postgres
  database: postgres
  port: 5432

persistence:
  enabled: true
  storageClass: "yc-network-hdd"
  size: "10Gi"
  accessModes: ["ReadWriteOnce"]
  labels:
    app: postgresql

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"

service:
  type: ClusterIP
  port: 5432