apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-postgresql
  labels:
    app: postgresql
    version: "12"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-postgresql
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-postgresql
    spec:
      containers:
      - name: postgresql
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.postgresql.port }}
        env:
        - name: POSTGRES_USER
          value: {{ .Values.postgresql.username | quote }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.postgresql.password | quote }}
        - name: POSTGRES_DB
          value: {{ .Values.postgresql.database | quote }}
        volumeMounts:
        - name: postgresql-data
          mountPath: /var/lib/postgresql/data/pgdata  # Ключевое изменение
          subPath: pgdata
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      volumes:
      - name: postgresql-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-postgresql-pvc